In [5]:
from sklearn import tree
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn import metrics
import numpy as np
import pandas as pd

#This is a program

In [4]:
data = pd.read_csv("/home/inder/Desktop/Machine Learning/fashionmnist/fashion-mnist_train.csv",nrows=1000)

NameError: name 'pd' is not defined

In [8]:
data.head()

label  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0      2       0       0       0       0       0       0       0       0   
1      9       0       0       0       0       0       0       0       0   
2      6       0       0       0       0       0       0       0       5   
3      0       0       0       0       1       2       0       0       0   
4      3       0       0       0       0       0       0       0       0   

   pixel9    ...     pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0        30        43   
3       0    ...            3         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  pixel784  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         1         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [5]:
data.columns

Index(['label', 'pixel1', 'pixel2', 'pixel3', 'pixel4', 'pixel5', 'pixel6',
       'pixel7', 'pixel8', 'pixel9',
       ...
       'pixel775', 'pixel776', 'pixel777', 'pixel778', 'pixel779', 'pixel780',
       'pixel781', 'pixel782', 'pixel783', 'pixel784'],
      dtype='object', length=785)

In [2]:
data.shape

NameError: name 'data' is not defined

In [3]:
data_train, data_valid = train_test_split(data, test_size=0.3, random_state=54)

NameError: name 'train_test_split' is not defined

In [11]:
data_train.shape

(42000, 785)

In [12]:
data_valid.shape

(18000, 785)

In [16]:
dt = tree.DecisionTreeClassifier()
dt.fit(data_train[data.columns[1:]], data_train['label'])
prediction = dt.predict(data_valid[data.columns[1:]])
pred=np.array
pred = np.insert(pred,column,trained_model.predict(X),axis=1)

In [17]:
prediction

array([2, 0, 8, ..., 0, 8, 5])

In [24]:
print("Confusion matrix", metrics.confusion_matrix(data_valid['label'], prediction))
print("Accuracy score:",metrics.accuracy_score(data_valid['label'], prediction))
print("Precision score:",metrics.precision_score(data_valid['label'], prediction,average='macro'))

Confusion matrix [[1373    8   38   72   24    5  294    1   26    2]
 [  18 1720    3   47   11    3   11    1    3    0]
 [  32    6 1185   41  272    2  234    0   21    1]
 [  82   60   30 1410  102    6   72    0    9    0]
 [  23    5  280   84 1170    1  202    0   26    0]
 [   0    4    2    2    1 1578    0  102   25   50]
 [ 261   12  219   69  206    1  999    1   36    2]
 [   0    0    0    0    0   92    0 1569   12  115]
 [  23    2   29   13   26   29   57   13 1556   11]
 [   2    3    1    1    1   43    2  111    3 1700]]
Accuracy score: 0.7922222222222223
Precision score: 0.7934391002605381
